### ISSUE TITLE
Pytanque installation fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by banescusebi** [quarkslab/arybo#1]
Hi,

I'm trying to install branch feature/exprs of Arybo and I'm getting the following error when I run the command to install pytanque: `sudo pip install pytanque`

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3EsubV/pytanque/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nseUJr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3EsubV/pytanque/`

Any ideas of how I could get passed this error or successfully install pytanque?

Thanks,
Sebastian

**Comment by aguinet** [comment]
Hello Sebastien,

"pip install pytanque" will install the stable version of pytanque uploaded on Pypi (this one https://pypi.python.org/pypi/pytanque/0.2.0), which should work with the feature/exprs version of Arybo.

The error you have is thus independent of this experimental branch and seems to be related to your Python installation. Which version of Python are you using ? Is this 32-bit or 64-bit ubuntu ?

Thanks :)

**Comment by banescusebi** [comment]
Thanks for you quick reply! I'm using Python 2.7.6 on a 64-bit Ubuntu.

**Comment by aguinet** [comment]
Okay ! Can you please try to reproduce this inside a virtualenv :

```
$ sudo apt-get install virtualenvwrapper
(reload your terminal then)
$ mkvirtualenv arybo-exp
$ workon arybo-expr
(arybo-exp) $ pip install pytanque
(arybo-exp) $ cd /path/to/arybo && python ./setup.py install
```

**Comment by banescusebi** [comment]
I've reproduced the issue in a virtualenv and attached the log of the last command.
[error-log.txt](https://github.com/quarkslab/arybo/files/567027/error-log.txt)

**Comment by aguinet** [comment]
Thanks ! This is a much better error message :)
It seems that the GCC compiler on Ubuntu 14.04 is too old and does not support C++14.

One workaround is to install a recent version of Clang using the official LLVM APT repositories here:
http://apt.llvm.org/ .

In a nutshell, add `deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main` to your /etc/apt/sources.list , then update apt (sudo apt-get update) and install clang-3.9 (sudo apt-get install clang-3.9).

You can then install pytanque using `CC=clang-3.9 CXX=clang++-3.9 pip install pytanque` .

Let me know if this solves your problem!

**Comment by banescusebi** [comment]
Thanks for your suggestion! Unfortunately, it seems that the following symbols are missing in clang-3.9 `gets, insert, emplace` (see attached error log). Any other suggestions? 
[error-log2.txt](https://github.com/quarkslab/arybo/files/567096/error-log2.txt)

**Comment by aguinet** [comment]
Okay the C++ library (listdc++) is also too old... :/
Try to install the paquets libc++-dev and libc++abi-dev and relaunch the installation.

I'm sorry I don't have any 14.04 ubuntu VM right now. If this doesn't work, I'll try to find a way tonight (in a few hours) !

**Comment by banescusebi** [comment]
Unfortunately, it doesn't work even after installing the two packages you mentioned. Thanks for your help!

**Comment by aguinet** [comment]
Okay i've got a solution thanks to @romainthomas !
We can install gcc 6.0 and the associated uptodate libstdc++ under Ubuntu 14.04 using a PPA;$

```
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get install g++-6
```

and then install pytanque like this:

```
$ CC=gcc-6 CXX=g++-6 pip install pytanque
```

**Comment by banescusebi** [comment]
Thanks a lot! That worked! Note that you also have to run `sudo apt-get update` after the first command.

**Comment by aguinet** [comment]
Okay nice :) I'll keep this one open 'till the documentation is updated for this!
