### ISSUE TITLE
Arybo does not support Python 2.7 in Windows

### ISSUE THREAD

**Issue by RyanLee1119** [quarkslab/arybo#12]
Trying to use Arybo in Windows with Triton, since Triton only support Python 2.7, I hope Arybo can fix Python 2.7 support in Windows

> with the exception of Python 2 not available under Windows
> https://pythonhosted.org/arybo/setup.html

Steps to reproduce in Windows:
1. install python-2.7.15.amd64
2. pip install arybo shows error compling pytanque:
   ` building 'pytanque' extension ... include\pa/exprs.h(30) : fatal error C1083: Cannot open include file: 'cstdint': No such file or directory`

Thanks

**Comment by aguinet** [comment]
I think now triton supports python3 cc @JonathanSalwan . Arybo will unlikely support easily Python 2 because of pytanque, which needs a recent C++ standard library which would not be provided by the visual studio verison you need to use to compile python2 extensions under Windows.

**Comment by JonathanSalwan** [comment]
Triton supports Python 2.7, 3.6, 3.7 and 3.8:

Python 2.7: `cmake -DPYTHON36=off`
Python 3.6: `cmake` (default setup)
Python 3.7: `cmake -DPYTHON37=on`
Python 3.8: `cmake -DPYTHON38=on`

**Comment by aguinet** [comment]
Okay thanks djo!
