### ISSUE TITLE
app_inverse for expressions with more than one symbols

### ISSUE THREAD

**Issue by NyaMisty** [quarkslab/arybo#8]
Thank you for building such a brilliant tool.
It seems that app_inverse does not support expressions with two or more symbols.
For example:
```
from arybo.lib import MBA
from arybo.tools import app_inverse
mba = MBA(32)
a = mba.var('a')
b = mba.var('b')
t = a & b
F = t.vectorial_decomp([a,b])
app_inverse(F) # returns None
```
Is there any workaround for this?

**Comment by aguinet** [comment]
Your original expression isn't invertible : `f(a,b) = a & b` isn't a bijective function. For instance, 5 & 1 == 1 and 3 & 1 == 1, so there is multiple invert to "1". That's why you have `None` as a result.
